import { useEffect, useState } from "react";
import { useParams } from "react-router-dom/cjs/react-router-dom.min";
import AddQuestions from "./AddQuestions";

const CreateTest = () => {
  const { company_id } = useParams();
  const [name, setName] = useState('');
  const [body, setBody] = useState('');
  const [questions, setQuestions] = useState([])
  const [test, setTest] = useState(null);

  useEffect(() => setTest(
    {
      //id of the test should be generated by the server
      "company_id": company_id,
      "name": name,
      "body": body,
      "questions": questions,
    }
  ), [company_id]);

  useEffect(() => {
    const updatedTest = {
      ...test,
      "name" : name,
      "body" : body,
      questions : questions
    };
    setTest(updatedTest);
  }, [name, body, questions]);

  const saveTest = () => {
    //TODO: send the test to the server
    console.log(test);
  };

  return (
    <div className="CreateTest container-md p-5 my-5 d-flex flex-column bg-secondary rounded">
        <div className="container-md py-3">
          <label htmlFor="test-name" className="form-label"> Name </label>
          <input type="text" className="form-control" id="test-name" value={name} onChange={(e) => setName(e.target.value)}/>
        </div>

        <div className="container-md py-3">
          <label htmlFor="test-body" className="form-label"> Test Info </label>
          <textarea className="form-control" id="test-body" rows="6" value={body} onChange={(e) => setBody(e.target.value)} />
        </div>

        <div className="container-md py-3 d-flex flex-column">
          <AddQuestions questions={questions} setQuestions={setQuestions} />
        </div>

        <button type="button" className="btn fs-3 align-self-center btn-outline-light" onClick={saveTest}>SAVE <i class="bi bi-floppy-fill"></i></button>
    </div>
  );
}

 
export default CreateTest;